### ISSUE TITLE
reconfiguring via `/boot/config.yml` file

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#53] opened 2017-07-31 11:44 UTC
[This image](http://liquidinvestigations.com/images/q2-exit/) has an implementation of reconfiguring via the `/boot/config.yml` file.

The code for that to happen is in the image itself, but not on any code repository.
We will need to move that into the setup repo.

**Comment by alsegno** [comment] 2017-08-21 11:31
This is part of #48

**Comment by alsegno** [comment] 2017-08-24 11:59
This is a duplicate of #48 :)

**Closed by alsegno** 2017-08-24 11:59 UTC
Labels: first boot, ready
