### ISSUE TITLE
Run arm64 VMs from the Odroid C2 disk image

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#117] opened 2017-09-20 19:14 UTC
This is needed to run tests in a VM on the image that resulted from the build process.

**Comment by gabriel-v** [comment] 2017-10-09 15:05
What this gets us is jenkins-driven tests that run against the nightly C2 image. We do not have these today.

**Comment by gabriel-v** [comment] 2017-10-09 15:12
Research into getting C2 bios files. If we don't find any, just cut off the bootloader partition.

**Comment by mgax** [comment] 2017-10-12 11:59
Closing as duplicate of #137.

**Closed by mgax** 2017-10-12 11:59 UTC
Labels: CI, ready
