### ISSUE TITLE
Odroid C2 nightly build broken

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#60] opened 2017-08-19 17:20 UTC
I have downloaded an appropriate BIOS file and I'm trying to run the nightly build on my local machine in qemu:

```
qemu-system-aarch64 -nographic -machine virt -m 1024 -bios ./QEMU_EFI.fd -device virtio-blk-device,drive=image -drive if=none,id=image,format=raw,file=./odroid_c2.img -cpu cortex-a53
```
This seems to do nothing.

**Comment by alsegno** [comment] 2017-08-19 17:20
If you know you're not going to work on this issue please remove yourself as an assignee.

**Comment by dreamlayers** [comment] 2017-08-23 00:49
The same partition resizing issue affecting the x86 build would be affecting the c2 build. Fix has been pushed to setup. For more info see https://github.com/liquidinvestigations/liquidinvestigations/issues/59#issuecomment-324185370

**Comment by alsegno** [comment] 2017-08-23 11:59
I think there's something wrong with my command line but I'm not sure what. Gabi/Boris have you been able to make this work with qemu?

**Comment by gabriel-v** [comment] 2017-08-23 12:13
I tried your command line yesterday with both yesterday's nightly and the q2 exit image. Both go into the UEFI BIOS command line. The q2 exit image is known to boot properly on the C2, so the problem is either with the command line or with the UEFI BIOS image.

**Comment by alsegno** [comment] 2017-08-23 13:30
Yeah, probably my mistake. I'll try it on a real c2 tomorrow.

**Comment by gabriel-v** [comment] 2017-08-24 09:54
Here's how buildbot actually runs qemu for emulating aarch64:

    /usr/bin/qemu-system-aarch64 -M virt -nographic -m 512 -netdev user,id=user,net=192.168.1.0/24,hostname=vm-aarch64,hostfwd=tcp::30955-:22 -device virtio-net-pci,netdev=user -bios ./images/arm-bios.fd -device virtio-blk-device,drive=image -drive if=none,id=image,snapshot=on,file=./images/disk.img -fsdev local,id=fsdev0,security_model=none,path=./shared -device virtio-9p-pci,fsdev=fsdev0,mount_tag=path0 -cpu cortex-a53

Maybe we want to increase the memory used for it.

**Comment by gabriel-v** [comment] 2017-08-25 16:27
The latest 25/08/2017 nightly boots on the Odroid C2. We won't be able to boot the nightly with the above command line, because the nightly image has a custom `/boot` partition for the Odroid C2 which does not work with qemu.

**Closed by gabriel-v** 2017-08-25 16:27 UTC
Labels: bug, in progress
